---

############################################################################################################################
#################################################### INFORMATION ###########################################################
############################################################################################################################

# All file paths accept absolute and relative paths
# Environment variables (including ~) are not processed, so don't use them in this config.


############################################################################################################################
############################################ RUN COMMON VARIABLES ##########################################################
############################################################################################################################

# BASE_OUTPUT_DIR: /scratch/mlf210/CELLECT-LDSC # for currect working directory use: ./CELLECT-LDSC
# Folder where all the output is saved (LD scores, prioritization results files, etc.) Directory will be created if it does not exists.
BASE_OUTPUT_DIR: ../results/cellect_magma/
  

### SPECIFICITY_INPUT: list of dictionaries
# id: identifier for the dataset. Output files will be prefixed with the id. MUST be unique and NO double underscores allowed
# path: the path to the matrix containing specificity scores for each genomic region, does not need to be unique
SPECIFICITY_INPUT:
  # - id: mousebrain-test
  #   path: /home/cbmr/nmq407/Code/CELLECT/example/mousebrain-test.csv.gz # 2 annotations
  # - id: tabula_muris-test
  #   path: example/tabula_muris-test.csv # 5 annotations
  - id: campbell2017_lvl1
    path: ../data/esmu/campbell2017_lvl1.mu.csv.gz
  - id: campbell2017_lvl2
    path: ../data/esmu/campbell2017_lvl2.mu.csv.gz
  - id: chen2017
    path: ../data/esmu/chen2017.mu.csv.gz
  - id: kimVMH2019_10x
    path: ../data/esmu/kimVMH2019_10x.mu.csv.gz
  - id: kimVMH2019_smartseq
    path: ../data/esmu/kimVMH2019_smartseq.mu.csv.gz
  - id: mikkelsen2019
    path: ../data/esmu/mikkelsen2019.mu.csv.gz
  - id: moffitt2018
    path: ../data/esmu/moffitt2018.mu.csv.gz
  - id: romanov2017
    path: ../data/esmu/romanov2017.mu.csv.gz  
  - id: mousebrain
    path: ../data/esmu/mousebrain.mu.csv.gz
  - id: tabula_muris
    path: ../data/esmu/tabula_muris.mu.csv.gz


### GWAS_SUMSTATS: list of dictionaries
# id: identifier for GWAS. MUST be unique and NO double underscores allowed
# path: filepath for munged GWAS sumstats.
# OBS: sumstats MUST be munged using the munge_sumstats.py script found in the LDSC repo.
GWAS_SUMSTATS:
  - id: pro
    path: ../data/munged_sumstats/pro.sumstats.gz
  - id: carb
    path: ../data/munged_sumstatscarb.sumstats.gz
  - id: fat
    path: ../data/munged_sumstatsfat.sumstats.gz

ANALYSIS_TYPE: # specify what analysis modes to run. At least one mode needs to be specified.
  prioritization: True # prioritizes all cell-type annotations in the SPECIFICITY_INPUT datasets
  conditional: False # performs conditional analysis for selected annotations.
  heritability: False # estimates heritability for selected annotations.
  heritability_intervals: False # estimates heritability intervals for selected annotations. 'heritability' must be True when enabling heritability_intervals


WINDOW_DEFINITION: # Window definition for mapping gene specificity values to SNPs
  WINDOW_SIZE_KB:
    100
  WINDOW_LD_BASED: # Will override WINDOW_SIZE_KB if True. If True, use LD-based 'window' to map SNPs to genes. 
    False

############################################################################################################################
############################################## CONDITIONAL ANALYSIS ########################################################
############################################################################################################################

### CONDITIONAL_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to condition on
# NOTE: you can delete or leave these dicts blank if the 'analysis type' is not activated
CONDITIONAL_INPUT:
  - id: mousebrain
    annotations: ['ABC']
  # - id: tabula_muris-test
  #   annotations: ['XX']


############################################################################################################################
###################################### HERITABILITY ANALYSIS (LDSC ONLY) ###################################################
############################################################################################################################

### HERITABILITY_INPUT: list of dictionaries
# id: dataset input - must correspond to an id in SPECIFICITY_INPUT.
# annotations: annotations to estimate heritability for
# NOTE: you can delete or leave these dicts blank if the 'analysis type' is not activated
HERITABILITY_INPUT:
  - id: mousebrain-test
    annotations: ['ABC']


#############################################################################################################################
##################################################### CONSTANTS #############################################################
#############################################################################################################################

# You generally do not need to change these variables.

LDSC_CONST:
  DATA_DIR: # Path to the data used for CELLECT-LDSC (baseline model, gene mapping etc).
    data/ldsc
  LDSC_DIR: # Path to the a cloned version of the github repo pascaltimshel/ldsc. This is included as a git submodule.
    ldsc
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via ithe '-j' flag.
    1


MAGMA_CONST:
  DATA_DIR: # Path to the data used for CELLECT-MAGMA (baseline model, gene mapping etc).
    data/magma
  NUMPY_CORES: # Numpy by default uses all cores available to it. This variable limits the amount of cores numpy can use to 1 so snakemake has full control over multicore processing via the '-j' flag.
    1

GENE_COORD_FILE: # Path to gene coordinates. First five columns must be: ensembl_gene_id, chromosome, start_position, stop_position, strand. No header allowed
  data/shared/gene_coordinates.GRCh37.ensembl_v91.txt


